apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-deployment
  labels:
    app.kubernetes.io/name: flask-demo-app
spec:
  replicas: 3  # Number of pod replicas
  selector:
    matchLabels:
      app.kubernetes.io/name: flask-demo-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: flask-demo-app
    spec:
      containers:
      - name: flask-pod-container
        image: flask_demo:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
