apiVersion: v1
kind: Service
metadata:
  name: demopod-svc
spec:
  selector:
    app.kubernetes.io/name: demopod
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 80
  type: NodePort