apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  selector:
    app.kubernetes.io/name: flask-demo-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: NodePort  # Expose the service using NodePort for local access